### ISSUE TITLE
棒！但是flutter版本目前要求太高

### ISSUE THREAD

**Issue by shuizhuyu1015** [moosoul/TXLiteAVSDK_Flutter#1]
yaml文件里面的flutter版本下限最好调低点老兄，1.20刚出不就，有些还在用年初的版本，基本在1.15到1.19，老兄可以设个1.15很多人都可以用啦

**Comment by moosoul** [comment]
可以，我也是做一个外包项目整的没太关注这个

**Comment by moosoul** [comment]
已降低flutter基础版本至1.10.0
